### ISSUE TITLE
Can't connect to a hidden SSID

### ISSUE THREAD

**Issue by Nelus82** [martijnvwezel/watermeter-esphome#21]
# Problem/Motivation

> My IoT network is a hidden SSID. I can't connect to this SSID.

When I connect to a non hidden SSID it is directly working. But when I want to adopt the device to my esphome it isn't working beause the standard SSID for esphome is a hidden one.

**Comment by martijnvwezel** [comment]
Its a esphome related, see following example what you need to add to your wifi

``` yaml
wifi:
  fast_connect: true
  hidden: true

```

for more background info [esphome-docs](https://esphome.io/components/wifi.html)

**Comment by martijnvwezel** [comment]
I will close the issue, becasue the issue is resolved
