### ISSUE TITLE
Sometimes issue with not counting liters correctly

### ISSUE THREAD

**Issue by martijnED** [martijnvwezel/watermeter-esphome#31]
Sometimes it is possible that due something weird the watermeter is not keeping correctly track of the usaged

**Comment by martijnED** [comment]
To my understanding the issue would possible be a min max problem in that sort. I have to investigate with the person who had this issue why the shift is there. I have the feeling that the part before using the water can have impact.

**Comment by martijnvwezel** [comment]
Close latest version solved
