### ISSUE TITLE
Lower updaterate of water usages to [X]min

### ISSUE THREAD

**Issue by martijnvwezel** [martijnvwezel/watermeter-esphome#34]
# Problem/Motivation

Solve bad connectivity issues skipping liters

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by martijnvwezel** [comment]
Currently, This is solved by using a timout when value has been update.

**Comment by martijnvwezel** [comment]
In latest dev branch this is build

**Comment by martijnED** [comment]
can be closed

**Comment by martijnvwezel** [comment]
Latest version has implemented this
