### ISSUE TITLE
Compatibility with my meter?

### ISSUE THREAD

**Issue by jurekjure** [martijnvwezel/watermeter-esphome#56]
Sorry for creating an issue, I could not find a contact to ask about compatibility of the meter.

I am attaching an image of my meter and am interested if it could work with your meter.
Thank you.
![a28bb5fd-5924-479b-9db3-d0a087dfd965](https://github.com/user-attachments/assets/86832ff8-61a5-4519-94e1-e9d02c4c1ec5)

**Comment by martijnED** [comment]
This is not possible.

**Comment by jurekjure** [comment]
Thanks for the repply

**Comment by 4np** [comment]
@jurekjure , it looks like this one may work: https://github.com/jomjol/AI-on-the-edge-device

**Comment by jurekjure** [comment]
@4np I know this one, but thank you!
